### ISSUE TITLE
extension broken

### ISSUE THREAD

**Issue by scicco** [husa/tab-groups#1]
Hello,

first of all thank you for this fantastic extension!

Sometimes the storage of the application brokes. According to a reply by Jose Vargas - Aug 22, 2018 in the [support page section](https://chrome.google.com/webstore/detail/tab-groups/hipnhfelcpeakkbodboaekadfleolnbi) it happens when the groupIds array key item inside chrome.storage.sync contains a groupid key that is not present inside the storage. When you click the extension button the popup will be empty. Following his steps will recover the extension storage data and make it work again.

Can you add an existence check inside the group load routine that prevents this edge case or rescue the exception and continue the load of the other group elements?

I hope to have been clear enough to help you understand the issue.

Thank you again for your efforts! 👍

**Comment by husa** [comment]
Hi @scicco, thanks for pointing this out.
I've seen the feedback and already know the "dirty" fix, but this behavior is really hard to reproduce. Will upload fixed version soon.
